// Expands tools/block-families.js into src/blocks/blocks.json.
//
//     npm run blocks
//
// It is also run automatically by `npm run dist`, ahead of `npm run styles`.
// The JSON is what ships; this script only exists so a colour or a theme is
// written down once instead of once per block.

const fs = require('fs');
const path = require('path');

const { blocks } = require('./block-families');

const rootDir = path.resolve(__dirname, '..');
const outPath = path.join(rootDir, 'src', 'blocks', 'blocks.json');

const MODES = [
	'card', 'callout', 'list', 'plain', 'quote', 'details', 'grid', 'steps',
	'timeline', 'stats', 'badges', 'keyvalue', 'progress', 'rating', 'table',
	'compare', 'faq', 'feature', 'chat',
];

const validate = () => {
	const taken = new Map();

	const claim = (name, block, kind) => {
		if (taken.has(name)) {
			throw new Error(`${kind} "${name}" on ${block.id} is already used by ${taken.get(name)}`);
		}
		taken.set(name, block.id);
	};

	for (const block of blocks) {
		if (!block.id) throw new Error(`Block without an id: ${JSON.stringify(block)}`);
		if (!/^[A-Za-z][A-Za-z0-9_-]*$/.test(block.id)) throw new Error(`Invalid id: ${block.id}`);
		if (!block.color) throw new Error(`Block without a colour: ${block.id}`);
		if (!block.label) throw new Error(`Block without a label: ${block.id}`);
		if (!block.category) throw new Error(`Block without a category: ${block.id}`);
		if (!MODES.includes(block.mode)) throw new Error(`Unknown mode "${block.mode}" on ${block.id}`);
		claim(block.id.toLowerCase(), block, 'Id');
	}

	// Aliases are claimed in a second pass: an alias may never shadow an id,
	// whichever order the two are declared in.
	for (const block of blocks) {
		for (const alias of block.aliases || []) claim(alias.toLowerCase(), block, 'Alias');
	}
};

/** Key order in the JSON, so diffs stay readable. */
const FIELD_ORDER = [
	'id', 'label', 'category', 'mode', 'theme', 'color', 'aliases', 'icon',
	'defaultTitle', 'variant', 'listStyle', 'ordered', 'columns', 'bare',
	'open', 'titleHint', 'bodyHint',
];

const clean = block => {
	const out = {};
	for (const field of FIELD_ORDER) {
		const value = block[field];
		if (value === undefined || value === null) continue;
		if (Array.isArray(value) && !value.length) continue;
		out[field] = value;
	}

	const unknown = Object.keys(block).filter(key => !FIELD_ORDER.includes(key));
	if (unknown.length) throw new Error(`Unknown field(s) on ${block.id}: ${unknown.join(', ')}`);

	return out;
};

validate();

const registry = {
	$comment: 'GENERATED by tools/generate-blocks.js from tools/block-families.js - do not edit by hand. Run `npm run blocks` (or `npm run dist`) after changing a family, then `npm run styles`.',
	blocks: blocks.map(clean),
};

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, `${JSON.stringify(registry, null, '\t')}\n`, 'utf8');

const categories = new Set(blocks.map(block => block.category));
console.info(`Wrote ${path.relative(rootDir, outPath)} - ${blocks.length} blocks in ${categories.size} categories`);
