// Builds the two stylesheets shipped with the plugin from the block registry,
// so colours only ever have to be declared once (in src/blocks/blocks.json).
//
//     npm run styles
//
// It is also run automatically by `npm run dist`.

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const registryPath = path.join(rootDir, 'src', 'blocks', 'blocks.json');

const targets = [
	{
		base: path.join(__dirname, 'styles', 'viewer-base.css'),
		out: path.join(rootDir, 'src', 'markdownItPlugin', 'style.css'),
		selector: id => `.jhtml-b-${id}`,
		unknownSelector: '.jhtml-unknown',
	},
	{
		base: path.join(__dirname, 'styles', 'editor-base.css'),
		out: path.join(rootDir, 'src', 'codeMirrorPlugin', 'style.css'),
		selector: id => `.cm-jhtml-b-${id}`,
		unknownSelector: '.cm-jhtml-b-unknown',
	},
];

const header = [
	'/* -------------------------------------------------------------------------',
	' * AUTO-GENERATED by tools/generate-styles.js - do not edit directly.',
	' * Edit tools/styles/*.css or src/blocks/blocks.json and run `npm run styles`.',
	' * ---------------------------------------------------------------------- */',
	'',
].join('\n');

const main = () => {
	const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
	const blocks = registry.blocks;

	const ids = new Set();
	for (const block of blocks) {
		if (!block.id || !block.color) throw new Error(`Block is missing an id or a color: ${JSON.stringify(block)}`);
		if (ids.has(block.id)) throw new Error(`Duplicate block id: ${block.id}`);
		ids.add(block.id);
	}

	for (const target of targets) {
		const lines = [
			header,
			fs.readFileSync(target.base, 'utf8').trim(),
			'',
			'/* --- per block colours (generated) --------------------------------------- */',
			'',
		];

		for (const block of blocks) {
			lines.push(`${target.selector(block.id)} { --jh-color: ${block.color}; }`);
		}

		lines.push(`${target.unknownSelector} { --jh-color: #94a3b8; }`);
		lines.push('');

		fs.mkdirSync(path.dirname(target.out), { recursive: true });
		fs.writeFileSync(target.out, lines.join('\n'), 'utf8');
		console.info(`Wrote ${path.relative(rootDir, target.out)} (${blocks.length} blocks)`);
	}
};

main();
